/** @type {import("tailwindcss").Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#7a0000",
        "surface-container": "#edeeec",
        "secondary-fixed-dim": "#ecc200",
        background: "#f8faf7",
        "error-container": "#ffdad6",
        "on-secondary-container": "#6e5900",
        "surface-variant": "#e1e3e1",
        "on-background": "#191c1b",
        "on-surface-variant": "#404941",
        "secondary-container": "#fdd000",
        "on-surface": "#191c1b",
        "surface-container-low": "#f2f4f2",
        "on-primary-container": "#75b085",
        "on-primary-fixed": "#002101",
        "primary-fixed-dim": "#97d4a7",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "inverse-primary": "#97d4a7",
        "secondary-fixed": "#ffe07c",
        "on-tertiary-fixed": "#410000",
        "inverse-surface": "#2e3130",
        "on-primary-fixed-variant": "#15512e",
        "on-secondary-fixed-variant": "#564500",
        "on-tertiary-fixed-variant": "#930000",
        outline: "#717971",
        outlineVariant: "#c0c9bf",
        "tertiary-fixed-dim": "#ffb4a8",
        "surface-container-high": "#e7e9e6",
        "surface-container-highest": "#e1e3e1",
        "on-secondary": "#ffffff",
        primary: "#002b14",
        "surface-tint": "#306944",
        tertiary: "#510000",
        "on-secondary-fixed": "#231b00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff7c69",
        "primary-container": "#004322",
        "tertiary-fixed": "#ffdad4",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#930000",
        "surface": "#f8faf7",
        "surface-bright": "#f8faf7",
        "surface-dim": "#d9dad8",
        "inverse-on-surface": "#f0f1ef",
        "primary-fixed": "#b3f1c2",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#404941",
        "on-tertiary-fixed": "#410000",
        "outline-variant": "#c0c9bf",
        "secondary-container": "#fdd000",
        secondary: "#725c00",
        "on-secondary-container": "#6e5900",
        "primary-fixed-dim": "#97d4a7",
        "on-primary-container": "#75b085",
        "tertiary-fixed-dim": "#ffb4a8",
        "tertiary-container": "#7a0000",
        "secondary-fixed-dim": "#ecc200",
        "secondary-fixed": "#ffe07c",
        "primary-container": "#004322",
        "secondary-fixed-variant": "#564500",
        "on-secondary-fixed-variant": "#564500",
        "on-secondary-fixed": "#231b00",
        "on-secondary-fixed-variant": "#564500",
        "on-surface-variant": "#404941",
        "on-background": "#191c1b",
        "on-surface": "#191c1b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff7c69",
        "on-tertiary-fixed": "#410000",
        "on-tertiary-fixed-variant": "#930000",
        "on-primary-fixed-variant": "#15512e",
        "on-secondary-fixed-variant": "#564500",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

